# -*- coding: utf-8 -*-
"""teachnook-assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sv07H9a9xocSPdBSKukTWLJrSavJWVHF
"""

# Assignment 1 
# Create a two different examples for collective datatypes in python

"""Set-
A Set is an unordered collection data type that is iterable, mutable, and has no duplicate elements
"""

Days = set(["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"])    
print(Days)    
print(type(Days))    
print("looping through the set elements ... ")    
for i in Days:    
    print(i)

Months = set(["January","February", "March", "April", "May", "June"])    
print("\nprinting the original set ... ")    
print(Months)    
print("\nAdding other months to the set...");    
Months.add("July");    
Months.add ("August");    
print("\nPrinting the modified set...");    
print(Months)    
print("\nlooping through the set elements ... ")    
for i in Months:    
    print(i)

"""Tuple-A tuple is a collection of objects which ordered and immutable. Tuples are sequences, just like lists"""

languages = ('Python', 'Swift', 'C++')


for language in languages:
    print(language)

my_tuple = ('p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z')

print(my_tuple[1:4])  


print(my_tuple[:-7]) 


print(my_tuple[7:]) 

print(my_tuple[:])

"""List-A list in Python is used to store the sequence of various types of data. A list can be defined as a collection of values or items of different types"""

thislist = ["apple", "banana", "cherry", "apple", "cherry"]
print(thislist)

my_list = ['p','r','o','g','r','a','m','i','z']

print(my_list[2:5])

print(my_list[5:])

print(my_list[:])

"""Dictionary-Dictionaries are Python's implementation of a data structure that is more generally known as an associative array"""

Dict = {1: 'Geeks', 2: 'For', 3: 'Geeks'}
print("\nDictionary with the use of Integer Keys: ")
print(Dict)

Dict = {'Name': 'Geeks', 1: [1, 2, 3, 4]}
print("\nDictionary with the use of Mixed Keys: ")
print(Dict)

Dict = {}
print("Empty Dictionary: ")
print(Dict)

Dict = dict({1: 'Geeks', 2: 'For', 3: 'Geeks'})
print("\nDictionary with the use of dict(): ")
print(Dict)
  
Dict = dict([(1, 'Geeks'), (2, 'For')])
print("\nDictionary with each item as a pair: ")
print(Dict)

"""# Assignment 2
Work on r+,W+,A+
"""

with open('a.txt', 'r+') as f:
    f.write("new line \n")

with open('a.txt', 'r+') as f:
    f.read()                # move file position to the end of the file.
    f.write("new line \n")

with open('a.txt', 'w+') as f:   
    f.write("test 1\n")
    f.write("test 2\n")
    f.write("test 3\n")

with open('file.txt', 'w+') as f:  
    f.write("test 1\n")
    f.write("test 2\n")
    f.write("test 3\n")             
    f.seek(0)                       
    lines = f.read()                
    print(lines)

with open('a.txt', 'a') as f:
    f.write("4")

with open('a.txt', 'a+') as f:
    f.seek(0)                       # file pointer at end, move to beginning
    lines = f.readlines()           # read all and file pointer at end again
    f.write("\n" + str(len(lines))) # append number of lines to a file